### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by mcelrath** [simonkamp/curve-trees#2]
It would be really good to have an example of how to use this code, and evolve it towards being a library.

To that end I have started a small example by trying to understand your tests and benchmarks. More examples would be welcome, or suggestions about this example!

    https://github.com/mcelrath/curve-trees-example/

Next I need to figure out how to do the Pedersen hashing so that the accumulator can contain arbitrary data, then move to demonstrating the ZKP membership proofs.

This is my first Rust code!

**Comment by simonkamp** [comment]
Hi.

While the purpose of this implementation was to benchmark the primitives I agree that it would be nice to have it available as a library. If nothing else, just to make BP which are generic over the curve and support vector commitments easily available. That could have saved us a lot of time. Unfortunately I don't at the moment have a lot of time to spend on this.

I am curious, are you interested in using this in production or as a building block for benchmarking other protocols? In case you want to use it for production it should probably be reviewed and documented as the current documentation is just provided as the delta from dalek. There are definitely a few quick fixes in the code that should be resolved.

Regarding the membership proofs I have not given too much thought towards what the right abstractions and API would be. I imagine we would just provide the gadgets for select-and-rerandomize and let the way you would build protocols from this be up to the user.

One task which would need to be handled is how to build and update the curve tree. Currently the implementation supports constructing a curve tree from a set of commitments, but does not have any methods for adding new commitments. It also stores every node in the tree. This is sufficient for benchmarking but in production you might only want to store the frontier of the tree and keep a witness ([CurveTreeWitnessPath](https://github.com/simonkamp/curve-trees/blob/46ff2ccd85da1837a50ef88ba0d407e442422dea/relations/src/curve_tree.rs#L385)) for each leaf you want to prove something about. If you only want to prove something against the current (as opposed to any previous) root of the tree you also need to write logic for updating the witnesses with the tree. All of this is fairly simple, but how to implement and optimize this data structure would be subject to a lot of use case specific choices. So we would probably only expose the `CurveTreeWitnessPath' to the user of the library and make them responsible for keeping the state.

I think it is a good idea to include some simple examples. If I understand what you were planning to do in your example, you want to add a set of strings to an accumulator? In that case you need to choose some way of encoding them as field elements. Then you would commit to them using Pedersen vector commitments with some fixed amount of generators and randomness zero [like here](https://github.com/simonkamp/curve-trees/blob/46ff2ccd85da1837a50ef88ba0d407e442422dea/relations/benches/accumulator.rs#L80C9-L80C24) and then make the point permissible [like here](https://github.com/simonkamp/curve-trees/blob/46ff2ccd85da1837a50ef88ba0d407e442422dea/relations/benches/accumulator.rs#L85).
How many generators you use determine (together with the height and branching factor of the tree) the capacity of the accumulator. It is also important that you either add an element to each generator in the commitments you put in the curve tree, or use some designated invalid element as padding. In the latter case remember to explicitly check for the invalid element in the circuit.
Let me know if you want help with any specific issues in your example :)

**Comment by simonkamp** [comment]
I realized that an alternative reading of your example is that you want to accumulate commitments to strings in a way that allows you to efficiently prove to someone that some (rerandomized) commitment is a commitment to one of the strings. Is that closer to what you had in mind?

**Comment by mcelrath** [comment]
We want to use your construction for a "proof of reserves" application. So the committed data is [<user_id>, <value>] where <user_id> is in F_p and <value> is numeric. We'd like to use range proofs on <value> to prove values are positive (semi-)definite, and additionally we'd like to be able to have a simple proof on the set of <value> that they sum to a value committed in the root of the tree, and possibly other algebraic constraints. More broadly, an analogous but non-ZK approach would be a tagged Merkle tree, but for now I'm going with just a single "tag" <user_id> and assuming we can create multiple Curve Trees for e.g. multiple assets instead of adding tags.

Your construction seems ideal for this but I'd appreciate any thoughts you have on using it this way. Your Vcash construction seems very very similar in committing to [<txid>, <value>]. We don't have a need to update commitments with a new root as you'd need in a blockchain (Well...maybe) nor adding elements, but publishing an entirely new root is acceptable here. All data to be committed is known at the outset and the Curve Tree is centrally created by a custodian or auditor. Audits would be periodic (daily/weekly/monthly) and I guess updating (or not) the root comes down to downloading a new set of witnesses, or downloading the root update data. Not sure which is larger/faster but no matter what we're talking about a relatively small amount of data and I think either would be fine for us. In both cases all clients need to download new data so it seems like a wash to me.

When proving blockchain data, we'd like to create something analogous to [Provisions](https://crypto.stanford.edu/~dabo/pubs/abstracts/provisions.html) though we also need to prove non-blockchain data such as liabilities, equity ownership (cap tables), etc.

Thanks for the tips, I'll keep working on it. Coming up with a user API is definitely desirable. I know this isn't production code but when we get to that point hopefully we can hire a code security audit firm.

Thanks!

**Comment by mcelrath** [comment]
BTW do you know in the lines you referenced, `leaf_commitment` and `permissible_point` and therefore `set` only have one element?  It looks like this code intended to keep the entire vector of leaf_elements. Maybe there's some template magic happening that I messed up.

Anyway, I added `map()` to have the Curve Tree commit to all values:
[https://github.com/mcelrath/curve-trees-example/blob/main/main.rs](https://github.com/mcelrath/curve-trees-example/blob/main/main.rs)

**Comment by simonkamp** [comment]
The referenced example is implementing zk set membership where the set just consists of known field elements. I initially thought that this was what you wanted to do. But I guess you want to hide `user_id` and `value`. In that case they would go in separate commitments, like in [this test](https://github.com/simonkamp/curve-trees/blob/4e94785ccb4e6cdce872d130b055f17e1db2d7ac/relations/src/coin.rs#L921) where two commitments representing coins are added to the tree. In that case they are blinded by a random scalar which is then incremented until the commitment becomes a permissible point [like here](https://github.com/simonkamp/curve-trees/blob/4e94785ccb4e6cdce872d130b055f17e1db2d7ac/relations/src/coin.rs#L67C1-L67C1).

I don't think I understand the use case, trust model and privacy concerns well enough to comment. Are the commitments produced by the user referenced by `user_id` and supposed to be hidden from the auditor? Is the full set of commitments publicly known, or is the auditor trusted to construct the curve tree correctly? Or maybe prove that they did so? Is the proof of the sum of the values supposed to be the sum of all values in the tree, or a sum for each `user_id`?

**Comment by mcelrath** [comment]
We don't necessarily need to hide `user_id` as it can be salted and hashed. In some cases it needs to be in the clear (like Bitcoin address). But in others I think a salt+hash is sufficient.

Value does generally need to be hidden. Do I need two trees for this and can I link the location in the `user_id` tree to the location in the `value` tree? 

The auditor (creator of the tree) has full visibility into all data and a proof that the tree was constructed properly is necessary.

The proof on sum of values is over the whole tree. Each `user_id` is unique and will appear exactly once in the tree. Where necessary, we can construct a second tree with the same `user_id`s. For example imagine a client has both a BTC and LTC balance, these would be two separate trees. (Or owns equity and is also in a payments outstanding tree). Different assets can't be summed, so they're different trees.
