### ISSUE TITLE
About Universal Hash implementation determinism

### ISSUE THREAD

**Issue by AdamISZ** [simonkamp/curve-trees#5]
This is a followup to #4 

In that context, I want Provers and Verifiers to be able to generate the same tree independently from a globally known key set (example: all taproot utxos from block 800K to 850K on the bitcoin blockchain). The `SelRerandParameters` object needed to instantiate a `CurveTree` [here](https://github.com/simonkamp/curve-trees/blob/620f19fa19c566ccb54e281faf760309a31f00d2/relations/src/curve_tree.rs#L29) takes an `rng` argument which is passed through into the UniversalHash constructor [here](https://github.com/simonkamp/curve-trees/blob/620f19fa19c566ccb54e281faf760309a31f00d2/relations/src/permissible.rs#L21), which uses this rng to generate the alpha and beta values.

Unless I got something wrong, this means that independent creations of a CurveTree object from the same set S will generate different trees (even if the set S has been preprocessed so that all points, used as leaves, are permissible). To allow my testing in the above-linked code repo to work, I just patched the UH constructor to use constants for alpha and beta.

What is the correct solution and/or did I misunderstand something about how the construction is intended to work?

**Comment by simonkamp** [comment]
Yes, you would fix some choice that the whole system uses.
But since then we have updated the implementation to get rid of the permissibility requirement by adding an independently sampled point to the children before committing to their x-coordinate.

**Comment by AdamISZ** [comment]
> Yes, you would fix some choice that the whole system uses. But since then we have updated the implementation to get rid of the permissibility requirement by adding an independently sampled point to the children before committing to their x-coordinate.

Great. Could I trouble you for a brief description of how that works? I'm very interested to know.

**Comment by matteocam** [comment]
> Could I trouble you for a brief description of how that works?

Hi Adam,
You should be able to find a description in our new work here:
https://eprint.iacr.org/2024/1647

**Comment by AdamISZ** [comment]
> > Could I trouble you for a brief description of how that works?
> 
> Hi Adam, You should be able to find a description in our new work here: https://eprint.iacr.org/2024/1647

Thanks.

Btw there seems to be an error in the paragraph "Security" at the end of Section 3:

> ... with x(C + ∆) = x(C ′ + ∆). But this implies
also y(C + ∆) = −y(C ′ + ∆) =⇒ C + ∆ = −C ′ + ∆ =⇒ C + C ′ = 0E ,

shouldn't it be C + ∆ = −(C ′ + ∆ ) so that the adversary would need a dlog (or better, representation) for ∆ ? Indeed, C + C' = 0 is not hard to arrange, given control over v and r in the two commitments :)

**Comment by matteocam** [comment]
Well spotted. Fixed!
